pipeline {
    agent any

    stages {

        stage('build') {
            steps {
              bat '''
                 cd ./retail-api-service
                 ./mvnw -DskipTests clean compile
              '''
            }
        }

        stage('test') {
            steps {
              bat '''
                 cd retail-api-service
                     ./mvnw test
              '''
            }
        }

        stage('deliver') {
            steps {
              bat '''
                 cd retail-api-service
                     ./mvnw -DskipTests install
              '''
            }
        }

    }
}
